spring:
    datasource:
        driverClassName: org.h2.Driver
        url: 'jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1'
        username: sa
        password: sa
        platform: h2
        initialization-mode: always
    h2:
        console:
            enabled: true
            path: /h2
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        show-sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
        properties:
            hibernate:
                hbm2ddl:
                    import_files: data.sql
